### ISSUE TITLE
请问怎么动态更换插件apk

### ISSUE THREAD

**Issue by JoinKing** [ManbangGroup/Phantom#19]
由于插件apk现在在是放在assets文件夹，我怎么动态更换插件apk

**Comment by Ccixyj** [comment]
通过服务器下发后，app下载至sd卡安装

**Comment by shaobin0604** [comment]
@JoinKing 将插件下载到设备上，内部存储或 SD 卡都可以，然后调用 `PhantomCore#installPlugin` 安装插件
