### ISSUE TITLE
plugin not  found

### ISSUE THREAD

**Issue by mrme2014** [ManbangGroup/Phantom#20]
ERROR: Could not find com.wlqq.phantom:phantom-gradle-plugin:3.1.3.
Searched in the following locations:
    file:/Users/timian/.m2/repository/com/wlqq/phantom/phantom-gradle-plugin/3.1.3/phantom-gradle-plugin-3.1.3.pom
    file:/Users/timian/.m2/repository/com/wlqq/phantom/phantom-gradle-plugin/3.1.3/phantom-gradle-plugin-3.1.3.jar
    http://maven.aliyun.com/com/wlqq/phantom/phantom-gradle-plugin/3.1.3/phantom-gradle-plugin-3.1.3.pom
    http://maven.aliyun.com/com/wlqq/phantom/phantom-gradle-plugin/3.1.3/phantom-gradle-plugin-3.1.3.jar
    https://jcenter.bintray.com/com/wlqq/phantom/phantom-gradle-plugin/3.1.3/phantom-gradle-plugin-3.1.3.pom
    https://jcenter.bintray.com/com/wlqq/phantom/phantom-gradle-plugin/3.1.3/phantom-gradle-plugin-3.1.3.jar
    https://dl.google.com/dl/android/maven2/com/wlqq/phantom/phantom-gradle-plugin/3.1.3/phantom-gradle-plugin-3.1.3.pom
    https://dl.google.com/dl/android/maven2/com/wlqq/phantom/phantom-gradle-plugin/3.1.3/phantom-gradle-plugin-3.1.3.jar
    https://repo.maven.apache.org/maven2/com/wlqq/phantom/phantom-gradle-plugin/3.1.3/phantom-gradle-plugin-3.1.3.pom
    https://repo.maven.apache.org/maven2/com/wlqq/phantom/phantom-gradle-plugin/3.1.3/phantom-gradle-plugin-3.1.3.jar
Required by:
    project :

下载的 GitHub master 分支的代码。打开工程的时候  androidstudio配置环境的时候 就会报这个错

**Comment by shaobin0604** [comment]
貌似是没有加到 jcenter ，本周修复
