### ISSUE TITLE
SO 的支持情况

### ISSUE THREAD

**Issue by CD3108** [ManbangGroup/Phantom#4]
SO 的支持是一大块。virtualAPK 支持的就不是很理想。科大讯飞的语音识别就只能放在宿主里，希望能出个支持清单。拜谢！

**Comment by shaobin0604** [comment]
> SO 的支持是一大块。virtualAPK 支持的就不是很理想。科大讯飞的语音识别就只能放在宿主里，希望能出个支持清单。拜谢！

感谢关注。

请查阅 https://github.com/ManbangGroup/Phantom/blob/master/docs/native.md
