### ISSUE TITLE
[Toolchain] 支持 Gradle 4.x + Android Gradle Plugin 3.x

### ISSUE THREAD

**Issue by shaobin0604** [ManbangGroup/Phantom#7]

**Comment by HubertYoung** [comment]
这个优化，大概什么时候能完成呢？？？

**Comment by shaobin0604** [comment]
@HubertYoung 计划 12 月上旬

**Comment by HubertYoung** [comment]
@shaobin0604 有什么书籍去学习相关知识？

**Comment by shaobin0604** [comment]
> @shaobin0604 有什么书籍去学习相关知识？

主要还是看同类型开源框架源码，以及涉及的相关软件源码（比如：Gradle, Gradle Android Plugin）

**Comment by HubertYoung** [comment]
好的，谢谢

**Comment by HubertYoung** [comment]
。。。。。

**Comment by shaobin0604** [comment]
Closed in 1f027f581a58b30ff17ba270730644d9ab9ad810
